// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9BsmNzbXJItd-iQT9CXLxDhlkXzCTeyk',
    appId: '1:1031604853481:android:4c82c1e17a2c8577146e78',
    messagingSenderId: '1031604853481',
    projectId: 'mychat-d1ce1',
    databaseURL: 'https://mychat-d1ce1-default-rtdb.firebaseio.com',
    storageBucket: 'mychat-d1ce1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALAQ2Y2yiPOj7WIFlJ3DhC_jiv7zcQAGA',
    appId: '1:1031604853481:ios:9470f16045dcc150146e78',
    messagingSenderId: '1031604853481',
    projectId: 'mychat-d1ce1',
    databaseURL: 'https://mychat-d1ce1-default-rtdb.firebaseio.com',
    storageBucket: 'mychat-d1ce1.appspot.com',
    androidClientId: '1031604853481-59pua9r3vbd86m0bvqts9gu1n7beu825.apps.googleusercontent.com',
    iosClientId: '1031604853481-c9k66eo4fbffivt8hre8hrikcbmup282.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
